map $http_origin $cors_origin {
    default "";

    "~^http://192\.168\.[0-9]+\.[0-9]+(:[0-9]+)?$" $http_origin;
    "~^http://10\.[0-9]+\.[0-9]+\.[0-9]+(:[0-9]+)?$" $http_origin;
    "~^http://172\.(1[6-9]|2[0-9]|3[0-1])\.[0-9]+\.[0-9]+(:[0-9]+)?$" $http_origin;
}