map $http_origin $cors_origin {
    default "";

    "~^https://(.*\.)?solucionescn\.com$" $http_origin;
    "https://app.sgc.solucionescn.com" $http_origin;
    "~^https://(.*\.)?hospitalposadas\.gob\.ar$" $http_origin;
}